name: Build artifact
on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: write
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        platform: [amd64, arm64]
        include:
          - platform: amd64
            runner: ubuntu-latest
          - platform: arm64
            runner: self-hosted,ubuntu-latest-arm64
    steps:
      - uses: actions/checkout@v2

      - name: run the buildscript
        run: /bin/sh build-static-tmux.sh -d

      - name: Upload artifacts
        uses: ncipollo/release-action@v1
        with:
          artifacts: "/tmp/tmux-static/bin/tmux.*.gz"
          replacesArtifacts: true
          allowUpdates: true
          bodyFile: "README.md"
          token: ${{ secrets.GITHUB_TOKEN }}
